# ==========================================================================
# update-claude-usage.ps1 - writes usage-data.js for the header usage widget
#
# Polls Anthropic's OAuth usage endpoint (the same one Claude Code's own
# Account & Usage panel uses) with the token Claude Code stores locally, and
# writes ONLY percentages / reset times / severity into usage-data.js at the
# app root (gitignored). Never writes, logs, or refreshes the token: if it is
# expired we exit and let the webapp's stale indicator report it - Claude Code
# refreshes the token itself the next time it is used.
#
# Register (every 10 minutes, hidden window). Run from cmd.exe - invoking
# schtasks from PowerShell mangles the escaped inner quotes and the task then
# fails on every run with result -196608:
#   schtasks /Create /F /TN "Anderson Homepage - Claude Usage" /SC MINUTE /MO 10 /TR "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"E:\My Apps\Anderson Homepage\tools\update-claude-usage.ps1\""
# Test:  powershell -NoProfile -ExecutionPolicy Bypass -File tools\update-claude-usage.ps1
# ==========================================================================

$ErrorActionPreference = 'Stop'

$appDir = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$outFile = Join-Path $appDir 'usage-data.js'

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# --- Read the Claude Code OAuth token (never emitted anywhere) -------------
$credFile = Join-Path $env:USERPROFILE '.claude\.credentials.json'
if (-not (Test-Path $credFile)) { exit 0 }
try {
    $oauth = (Get-Content $credFile -Raw | ConvertFrom-Json).claudeAiOauth
} catch { exit 0 }
if ($null -eq $oauth -or [string]::IsNullOrEmpty($oauth.accessToken)) { exit 0 }

# Skip (don't refresh) an expired/near-expiry token; stale UI reports it.
$nowMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
if ($oauth.expiresAt -le ($nowMs + 60000)) { exit 0 }

# --- Query the usage endpoint ----------------------------------------------
# -MaximumRedirection 0 fails closed: PS 5.1 would otherwise re-send the
# Authorization header to wherever a 3xx pointed.
try {
    $resp = Invoke-RestMethod -Uri 'https://api.anthropic.com/api/oauth/usage' -Method Get `
        -MaximumRedirection 0 -TimeoutSec 30 -Headers @{
        'Authorization'  = "Bearer $($oauth.accessToken)"
        'anthropic-beta' = 'oauth-2025-04-20'
    }
} catch { exit 0 }   # network/API failure/redirect: keep the previous file
if ($null -eq $resp.limits) { exit 0 }

# --- Map the limits we display ---------------------------------------------
$labels = @{ session = 'Session'; weekly_all = 'Week' }
$limits = @()
foreach ($l in $resp.limits) {
    $label = $null
    if ($labels.ContainsKey([string]$l.kind)) {
        $label = $labels[[string]$l.kind]
    } elseif ($l.kind -eq 'weekly_scoped' -and $l.scope.model.display_name -eq 'Fable') {
        $label = 'Fable (Week)'
    }
    if ($null -eq $label) { continue }   # other scoped limits not shown
    $limits += [ordered]@{
        kind     = $l.kind
        label    = $label
        percent  = [math]::Round([double]$l.percent, 1)
        resetsAt = [string]$l.resets_at
        severity = [string]$l.severity
    }
}
if ($limits.Count -eq 0) { exit 0 }

$payload = [ordered]@{
    fetchedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    limits    = $limits
}

$content = "// Generated by tools/update-claude-usage.ps1 - do not edit; gitignored.`n" +
           'window.ClaudeUsage = ' + (ConvertTo-Json $payload -Depth 5) + ';' + "`n"

# --- Atomic write (UTF-8 no BOM) so the browser never reads a partial file -
$tmp = "$outFile.tmp"
[IO.File]::WriteAllText($tmp, $content, (New-Object Text.UTF8Encoding($false)))
try { Move-Item -Force $tmp $outFile }
catch {
    # Destination momentarily locked by a reader: retry once, else clean up
    # the temp file and keep the previous data.
    Start-Sleep -Milliseconds 250
    try { Move-Item -Force $tmp $outFile }
    catch { try { Remove-Item $tmp -Force -ErrorAction Stop } catch {} }
}
exit 0
