# ==========================================================================
# update-claude-usage.ps1 - writes usage-data.js for the header usage widget
#
# Polls Anthropic's OAuth usage endpoint (the same one Claude Code's own
# Account & Usage panel uses) with the token Claude Code stores locally, and
# writes ONLY percentages / reset times / severity into usage-data.js at the
# app root (gitignored). Never writes, logs, or refreshes the token: if it is
# expired we keep the previous limits and let the webapp's stale indicator
# report it - Claude Code refreshes the token itself the next time it is used.
#
# Every run that finds a previous payload re-stamps `checkedAt` (and a
# `tokenExpired` flag), carrying the previous fetch forward untouched when no
# new one is possible. `fetchedAt` moves only on a successful fetch. The
# widget uses the gap between the two to name the stale cause: fresh
# checkedAt + tokenExpired means "open Claude Code", fresh checkedAt alone
# means the fetch itself failed, and a stale checkedAt means this task isn't
# running at all (battery, sleep, broken registration). A missing or
# unreadable credentials file counts as an expired login - /logout and
# "never logged in" need the same fix as an expired token.
#
# Register (every 10 minutes, hidden window). Run from cmd.exe - invoking
# schtasks from PowerShell mangles the escaped inner quotes and the task then
# fails on every run with result -196608:
#   schtasks /Create /F /TN "Anderson Homepage - Claude Usage" /SC MINUTE /MO 10 /TR "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"E:\My Apps\Anderson Homepage\tools\update-claude-usage.ps1\""
# Test:  powershell -NoProfile -ExecutionPolicy Bypass -File tools\update-claude-usage.ps1
# ==========================================================================

$ErrorActionPreference = 'Stop'

# The always-exit-0 invariant, enforced last-resort: with EAP=Stop any stray
# error (disk full, AV holding the tmp file, ConvertTo-Json) would otherwise
# terminate the script non-zero from inside a bail-out path.
trap { exit 0 }

$appDir = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$outFile = Join-Path $appDir 'usage-data.js'

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$nowIso = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

# --- Atomic write (UTF-8 no BOM) so the browser never reads a partial file -
function Write-UsageFile($payload) {
    $content = "// Generated by tools/update-claude-usage.ps1 - do not edit; gitignored.`n" +
               'window.ClaudeUsage = ' + (ConvertTo-Json $payload -Depth 5) + ';' + "`n"
    $tmp = "$outFile.tmp"
    [IO.File]::WriteAllText($tmp, $content, (New-Object Text.UTF8Encoding($false)))
    try { Move-Item -Force $tmp $outFile }
    catch {
        # Destination momentarily locked by a reader: retry once, else clean up
        # the temp file and keep the previous data.
        Start-Sleep -Milliseconds 250
        try { Move-Item -Force $tmp $outFile }
        catch { try { Remove-Item $tmp -Force -ErrorAction Stop } catch {} }
    }
}

# The previous payload, parsed back out of the generated file - $null if the
# file is missing or unreadable (fresh clone, hand-edited, mid-write).
function Read-OldUsage {
    if (-not (Test-Path $outFile)) { return $null }
    try {
        $m = [regex]::Match([IO.File]::ReadAllText($outFile), '(?s)window\.ClaudeUsage\s*=\s*(\{.*\});')
        if (-not $m.Success) { return $null }
        return (ConvertFrom-Json $m.Groups[1].Value)
    } catch { return $null }
}

# No new fetch this run: re-emit the old limits with a fresh checkedAt so the
# widget knows the task is alive, plus why there is nothing newer. With no old
# data there is nothing to annotate - the widget is still hidden anyway.
function Write-StatusOnly([bool]$expired) {
    $old = Read-OldUsage
    if ($null -eq $old -or $null -eq $old.limits) { return }
    Write-UsageFile ([ordered]@{
        fetchedAt    = [string]$old.fetchedAt
        checkedAt    = $nowIso
        tokenExpired = $expired
        limits       = @($old.limits)   # @() keeps a single limit an array in JSON
    })
}

# --- Read the Claude Code OAuth token (never emitted anywhere) -------------
# Missing/unreadable/empty credentials are reported as an expired login, not
# silence - the user-visible fix (open Claude Code) is the same.
$credFile = Join-Path $env:USERPROFILE '.claude\.credentials.json'
if (-not (Test-Path $credFile)) { Write-StatusOnly $true; exit 0 }
try {
    $oauth = (Get-Content $credFile -Raw | ConvertFrom-Json).claudeAiOauth
} catch { Write-StatusOnly $true; exit 0 }
if ($null -eq $oauth -or [string]::IsNullOrEmpty($oauth.accessToken)) { Write-StatusOnly $true; exit 0 }

# Skip (don't refresh) an expired/near-expiry token; stale UI reports it.
$nowMs = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
if ($oauth.expiresAt -le ($nowMs + 60000)) { Write-StatusOnly $true; exit 0 }

# --- Query the usage endpoint ----------------------------------------------
# -MaximumRedirection 0 fails closed: PS 5.1 would otherwise re-send the
# Authorization header to wherever a 3xx pointed.
try {
    $resp = Invoke-RestMethod -Uri 'https://api.anthropic.com/api/oauth/usage' -Method Get `
        -MaximumRedirection 0 -TimeoutSec 30 -Headers @{
        'Authorization'  = "Bearer $($oauth.accessToken)"
        'anthropic-beta' = 'oauth-2025-04-20'
    }
} catch { Write-StatusOnly $false; exit 0 }   # network/API failure/redirect: keep the previous limits
if ($null -eq $resp.limits) { Write-StatusOnly $false; exit 0 }

# --- Map the limits we display ---------------------------------------------
$labels = @{ session = 'Session'; weekly_all = 'Week' }
$limits = @()
foreach ($l in $resp.limits) {
    $label = $null
    if ($labels.ContainsKey([string]$l.kind)) {
        $label = $labels[[string]$l.kind]
    } elseif ($l.kind -eq 'weekly_scoped' -and $l.scope.model.display_name -eq 'Fable') {
        $label = 'Fable (Week)'
    }
    if ($null -eq $label) { continue }   # other scoped limits not shown
    $limits += [ordered]@{
        kind     = $l.kind
        label    = $label
        percent  = [math]::Round([double]$l.percent, 1)
        resetsAt = [string]$l.resets_at
        severity = [string]$l.severity
    }
}
if ($limits.Count -eq 0) { Write-StatusOnly $false; exit 0 }

Write-UsageFile ([ordered]@{
    fetchedAt    = $nowIso
    checkedAt    = $nowIso
    tokenExpired = $false
    limits       = @($limits)
})
exit 0
